export const todoActions = {
    ADD_TODO:"ADD_TODO_REQUEST",
    GET_TODO_REQUEST:"GET_TODO_REQUEST",
    GET_TODO_SUCCESS:"GET_TODO_SUCCESS",
    GET_TODO_FAILURE:"GET_TODO_FAILURE",
    ADD_TODO_REQUEST:"ADD_TODO_REQUEST",
    ADD_TODO_FAILURE:"ADD_TODO_FAILURE",
    ADD_TODO_SUCCESS:"ADD_TODO_SUCCESS"
}