"use client";
import "./global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}  className={inter.className}>
        {pathName !== "/about/college" ? (
          <ul className={"login"}>
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/about"}>About</Link>
            </li>
            <li>
              <Link href={"/about/student"}>Student</Link>
            </li>
            <li>
              <Link href={"/about/college"}>College</Link>
            </li>
          </ul>
        ) : null}

        {children}
      </body>
    </html>
  );
}
